# Generated by Django 5.0.7 on 2024-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_pages', models.JSONField()),
                ('country', models.CharField(max_length=50)),
                ('state_province', models.CharField(blank=True, max_length=50, null=True)),
                ('domains', models.JSONField()),
                ('alpha_two_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
